# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/camilo/solution/basis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/camilo/solution/basis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/camilo/solution/basis && $(CMAKE_COMMAND) -E cmake_progress_start /home/camilo/solution/basis/CMakeFiles /home/camilo/solution/basis/source/port/id3lib//CMakeFiles/progress.marks
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 source/port/id3lib/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/camilo/solution/basis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 source/port/id3lib/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 source/port/id3lib/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 source/port/id3lib/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/camilo/solution/basis && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
source/port/id3lib/CMakeFiles/id3lib.dir/rule:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 source/port/id3lib/CMakeFiles/id3lib.dir/rule
.PHONY : source/port/id3lib/CMakeFiles/id3lib.dir/rule

# Convenience name for target.
id3lib: source/port/id3lib/CMakeFiles/id3lib.dir/rule
.PHONY : id3lib

# fast build rule for target.
id3lib/fast:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/build
.PHONY : id3lib/fast

ca2_readers.o: ca2_readers.cpp.o
.PHONY : ca2_readers.o

# target to build an object file
ca2_readers.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/ca2_readers.cpp.o
.PHONY : ca2_readers.cpp.o

ca2_readers.i: ca2_readers.cpp.i
.PHONY : ca2_readers.i

# target to preprocess a source file
ca2_readers.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/ca2_readers.cpp.i
.PHONY : ca2_readers.cpp.i

ca2_readers.s: ca2_readers.cpp.s
.PHONY : ca2_readers.s

# target to generate assembly for a file
ca2_readers.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/ca2_readers.cpp.s
.PHONY : ca2_readers.cpp.s

# target to build an object file
cmake_pch.hxx.gch:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

src/field.o: src/field.cpp.o
.PHONY : src/field.o

# target to build an object file
src/field.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field.cpp.o
.PHONY : src/field.cpp.o

src/field.i: src/field.cpp.i
.PHONY : src/field.i

# target to preprocess a source file
src/field.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field.cpp.i
.PHONY : src/field.cpp.i

src/field.s: src/field.cpp.s
.PHONY : src/field.s

# target to generate assembly for a file
src/field.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field.cpp.s
.PHONY : src/field.cpp.s

src/field_binary.o: src/field_binary.cpp.o
.PHONY : src/field_binary.o

# target to build an object file
src/field_binary.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_binary.cpp.o
.PHONY : src/field_binary.cpp.o

src/field_binary.i: src/field_binary.cpp.i
.PHONY : src/field_binary.i

# target to preprocess a source file
src/field_binary.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_binary.cpp.i
.PHONY : src/field_binary.cpp.i

src/field_binary.s: src/field_binary.cpp.s
.PHONY : src/field_binary.s

# target to generate assembly for a file
src/field_binary.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_binary.cpp.s
.PHONY : src/field_binary.cpp.s

src/field_integer.o: src/field_integer.cpp.o
.PHONY : src/field_integer.o

# target to build an object file
src/field_integer.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_integer.cpp.o
.PHONY : src/field_integer.cpp.o

src/field_integer.i: src/field_integer.cpp.i
.PHONY : src/field_integer.i

# target to preprocess a source file
src/field_integer.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_integer.cpp.i
.PHONY : src/field_integer.cpp.i

src/field_integer.s: src/field_integer.cpp.s
.PHONY : src/field_integer.s

# target to generate assembly for a file
src/field_integer.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_integer.cpp.s
.PHONY : src/field_integer.cpp.s

src/field_string_ascii.o: src/field_string_ascii.cpp.o
.PHONY : src/field_string_ascii.o

# target to build an object file
src/field_string_ascii.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_string_ascii.cpp.o
.PHONY : src/field_string_ascii.cpp.o

src/field_string_ascii.i: src/field_string_ascii.cpp.i
.PHONY : src/field_string_ascii.i

# target to preprocess a source file
src/field_string_ascii.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_string_ascii.cpp.i
.PHONY : src/field_string_ascii.cpp.i

src/field_string_ascii.s: src/field_string_ascii.cpp.s
.PHONY : src/field_string_ascii.s

# target to generate assembly for a file
src/field_string_ascii.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_string_ascii.cpp.s
.PHONY : src/field_string_ascii.cpp.s

src/field_string_unicode.o: src/field_string_unicode.cpp.o
.PHONY : src/field_string_unicode.o

# target to build an object file
src/field_string_unicode.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_string_unicode.cpp.o
.PHONY : src/field_string_unicode.cpp.o

src/field_string_unicode.i: src/field_string_unicode.cpp.i
.PHONY : src/field_string_unicode.i

# target to preprocess a source file
src/field_string_unicode.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_string_unicode.cpp.i
.PHONY : src/field_string_unicode.cpp.i

src/field_string_unicode.s: src/field_string_unicode.cpp.s
.PHONY : src/field_string_unicode.s

# target to generate assembly for a file
src/field_string_unicode.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/field_string_unicode.cpp.s
.PHONY : src/field_string_unicode.cpp.s

src/frame.o: src/frame.cpp.o
.PHONY : src/frame.o

# target to build an object file
src/frame.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame.cpp.o
.PHONY : src/frame.cpp.o

src/frame.i: src/frame.cpp.i
.PHONY : src/frame.i

# target to preprocess a source file
src/frame.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame.cpp.i
.PHONY : src/frame.cpp.i

src/frame.s: src/frame.cpp.s
.PHONY : src/frame.s

# target to generate assembly for a file
src/frame.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame.cpp.s
.PHONY : src/frame.cpp.s

src/frame_impl.o: src/frame_impl.cpp.o
.PHONY : src/frame_impl.o

# target to build an object file
src/frame_impl.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_impl.cpp.o
.PHONY : src/frame_impl.cpp.o

src/frame_impl.i: src/frame_impl.cpp.i
.PHONY : src/frame_impl.i

# target to preprocess a source file
src/frame_impl.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_impl.cpp.i
.PHONY : src/frame_impl.cpp.i

src/frame_impl.s: src/frame_impl.cpp.s
.PHONY : src/frame_impl.s

# target to generate assembly for a file
src/frame_impl.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_impl.cpp.s
.PHONY : src/frame_impl.cpp.s

src/frame_parse.o: src/frame_parse.cpp.o
.PHONY : src/frame_parse.o

# target to build an object file
src/frame_parse.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_parse.cpp.o
.PHONY : src/frame_parse.cpp.o

src/frame_parse.i: src/frame_parse.cpp.i
.PHONY : src/frame_parse.i

# target to preprocess a source file
src/frame_parse.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_parse.cpp.i
.PHONY : src/frame_parse.cpp.i

src/frame_parse.s: src/frame_parse.cpp.s
.PHONY : src/frame_parse.s

# target to generate assembly for a file
src/frame_parse.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_parse.cpp.s
.PHONY : src/frame_parse.cpp.s

src/frame_render.o: src/frame_render.cpp.o
.PHONY : src/frame_render.o

# target to build an object file
src/frame_render.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_render.cpp.o
.PHONY : src/frame_render.cpp.o

src/frame_render.i: src/frame_render.cpp.i
.PHONY : src/frame_render.i

# target to preprocess a source file
src/frame_render.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_render.cpp.i
.PHONY : src/frame_render.cpp.i

src/frame_render.s: src/frame_render.cpp.s
.PHONY : src/frame_render.s

# target to generate assembly for a file
src/frame_render.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/frame_render.cpp.s
.PHONY : src/frame_render.cpp.s

src/globals.o: src/globals.cpp.o
.PHONY : src/globals.o

# target to build an object file
src/globals.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/globals.cpp.o
.PHONY : src/globals.cpp.o

src/globals.i: src/globals.cpp.i
.PHONY : src/globals.i

# target to preprocess a source file
src/globals.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/globals.cpp.i
.PHONY : src/globals.cpp.i

src/globals.s: src/globals.cpp.s
.PHONY : src/globals.s

# target to generate assembly for a file
src/globals.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/globals.cpp.s
.PHONY : src/globals.cpp.s

src/header.o: src/header.cpp.o
.PHONY : src/header.o

# target to build an object file
src/header.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header.cpp.o
.PHONY : src/header.cpp.o

src/header.i: src/header.cpp.i
.PHONY : src/header.i

# target to preprocess a source file
src/header.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header.cpp.i
.PHONY : src/header.cpp.i

src/header.s: src/header.cpp.s
.PHONY : src/header.s

# target to generate assembly for a file
src/header.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header.cpp.s
.PHONY : src/header.cpp.s

src/header_frame.o: src/header_frame.cpp.o
.PHONY : src/header_frame.o

# target to build an object file
src/header_frame.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header_frame.cpp.o
.PHONY : src/header_frame.cpp.o

src/header_frame.i: src/header_frame.cpp.i
.PHONY : src/header_frame.i

# target to preprocess a source file
src/header_frame.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header_frame.cpp.i
.PHONY : src/header_frame.cpp.i

src/header_frame.s: src/header_frame.cpp.s
.PHONY : src/header_frame.s

# target to generate assembly for a file
src/header_frame.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header_frame.cpp.s
.PHONY : src/header_frame.cpp.s

src/header_tag.o: src/header_tag.cpp.o
.PHONY : src/header_tag.o

# target to build an object file
src/header_tag.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header_tag.cpp.o
.PHONY : src/header_tag.cpp.o

src/header_tag.i: src/header_tag.cpp.i
.PHONY : src/header_tag.i

# target to preprocess a source file
src/header_tag.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header_tag.cpp.i
.PHONY : src/header_tag.cpp.i

src/header_tag.s: src/header_tag.cpp.s
.PHONY : src/header_tag.s

# target to generate assembly for a file
src/header_tag.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/header_tag.cpp.s
.PHONY : src/header_tag.cpp.s

src/helpers.o: src/helpers.cpp.o
.PHONY : src/helpers.o

# target to build an object file
src/helpers.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/helpers.cpp.o
.PHONY : src/helpers.cpp.o

src/helpers.i: src/helpers.cpp.i
.PHONY : src/helpers.i

# target to preprocess a source file
src/helpers.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/helpers.cpp.i
.PHONY : src/helpers.cpp.i

src/helpers.s: src/helpers.cpp.s
.PHONY : src/helpers.s

# target to generate assembly for a file
src/helpers.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/helpers.cpp.s
.PHONY : src/helpers.cpp.s

src/io.o: src/io.cpp.o
.PHONY : src/io.o

# target to build an object file
src/io.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io.cpp.o
.PHONY : src/io.cpp.o

src/io.i: src/io.cpp.i
.PHONY : src/io.i

# target to preprocess a source file
src/io.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io.cpp.i
.PHONY : src/io.cpp.i

src/io.s: src/io.cpp.s
.PHONY : src/io.s

# target to generate assembly for a file
src/io.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io.cpp.s
.PHONY : src/io.cpp.s

src/io_decorators.o: src/io_decorators.cpp.o
.PHONY : src/io_decorators.o

# target to build an object file
src/io_decorators.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io_decorators.cpp.o
.PHONY : src/io_decorators.cpp.o

src/io_decorators.i: src/io_decorators.cpp.i
.PHONY : src/io_decorators.i

# target to preprocess a source file
src/io_decorators.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io_decorators.cpp.i
.PHONY : src/io_decorators.cpp.i

src/io_decorators.s: src/io_decorators.cpp.s
.PHONY : src/io_decorators.s

# target to generate assembly for a file
src/io_decorators.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io_decorators.cpp.s
.PHONY : src/io_decorators.cpp.s

src/io_helpers.o: src/io_helpers.cpp.o
.PHONY : src/io_helpers.o

# target to build an object file
src/io_helpers.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io_helpers.cpp.o
.PHONY : src/io_helpers.cpp.o

src/io_helpers.i: src/io_helpers.cpp.i
.PHONY : src/io_helpers.i

# target to preprocess a source file
src/io_helpers.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io_helpers.cpp.i
.PHONY : src/io_helpers.cpp.i

src/io_helpers.s: src/io_helpers.cpp.s
.PHONY : src/io_helpers.s

# target to generate assembly for a file
src/io_helpers.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/io_helpers.cpp.s
.PHONY : src/io_helpers.cpp.s

src/misc_support.o: src/misc_support.cpp.o
.PHONY : src/misc_support.o

# target to build an object file
src/misc_support.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/misc_support.cpp.o
.PHONY : src/misc_support.cpp.o

src/misc_support.i: src/misc_support.cpp.i
.PHONY : src/misc_support.i

# target to preprocess a source file
src/misc_support.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/misc_support.cpp.i
.PHONY : src/misc_support.cpp.i

src/misc_support.s: src/misc_support.cpp.s
.PHONY : src/misc_support.s

# target to generate assembly for a file
src/misc_support.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/misc_support.cpp.s
.PHONY : src/misc_support.cpp.s

src/mp3_parse.o: src/mp3_parse.cpp.o
.PHONY : src/mp3_parse.o

# target to build an object file
src/mp3_parse.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/mp3_parse.cpp.o
.PHONY : src/mp3_parse.cpp.o

src/mp3_parse.i: src/mp3_parse.cpp.i
.PHONY : src/mp3_parse.i

# target to preprocess a source file
src/mp3_parse.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/mp3_parse.cpp.i
.PHONY : src/mp3_parse.cpp.i

src/mp3_parse.s: src/mp3_parse.cpp.s
.PHONY : src/mp3_parse.s

# target to generate assembly for a file
src/mp3_parse.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/mp3_parse.cpp.s
.PHONY : src/mp3_parse.cpp.s

src/readers.o: src/readers.cpp.o
.PHONY : src/readers.o

# target to build an object file
src/readers.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/readers.cpp.o
.PHONY : src/readers.cpp.o

src/readers.i: src/readers.cpp.i
.PHONY : src/readers.i

# target to preprocess a source file
src/readers.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/readers.cpp.i
.PHONY : src/readers.cpp.i

src/readers.s: src/readers.cpp.s
.PHONY : src/readers.s

# target to generate assembly for a file
src/readers.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/readers.cpp.s
.PHONY : src/readers.cpp.s

src/spec.o: src/spec.cpp.o
.PHONY : src/spec.o

# target to build an object file
src/spec.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/spec.cpp.o
.PHONY : src/spec.cpp.o

src/spec.i: src/spec.cpp.i
.PHONY : src/spec.i

# target to preprocess a source file
src/spec.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/spec.cpp.i
.PHONY : src/spec.cpp.i

src/spec.s: src/spec.cpp.s
.PHONY : src/spec.s

# target to generate assembly for a file
src/spec.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/spec.cpp.s
.PHONY : src/spec.cpp.s

src/tag.o: src/tag.cpp.o
.PHONY : src/tag.o

# target to build an object file
src/tag.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag.cpp.o
.PHONY : src/tag.cpp.o

src/tag.i: src/tag.cpp.i
.PHONY : src/tag.i

# target to preprocess a source file
src/tag.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag.cpp.i
.PHONY : src/tag.cpp.i

src/tag.s: src/tag.cpp.s
.PHONY : src/tag.s

# target to generate assembly for a file
src/tag.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag.cpp.s
.PHONY : src/tag.cpp.s

src/tag_file.o: src/tag_file.cpp.o
.PHONY : src/tag_file.o

# target to build an object file
src/tag_file.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_file.cpp.o
.PHONY : src/tag_file.cpp.o

src/tag_file.i: src/tag_file.cpp.i
.PHONY : src/tag_file.i

# target to preprocess a source file
src/tag_file.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_file.cpp.i
.PHONY : src/tag_file.cpp.i

src/tag_file.s: src/tag_file.cpp.s
.PHONY : src/tag_file.s

# target to generate assembly for a file
src/tag_file.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_file.cpp.s
.PHONY : src/tag_file.cpp.s

src/tag_find.o: src/tag_find.cpp.o
.PHONY : src/tag_find.o

# target to build an object file
src/tag_find.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_find.cpp.o
.PHONY : src/tag_find.cpp.o

src/tag_find.i: src/tag_find.cpp.i
.PHONY : src/tag_find.i

# target to preprocess a source file
src/tag_find.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_find.cpp.i
.PHONY : src/tag_find.cpp.i

src/tag_find.s: src/tag_find.cpp.s
.PHONY : src/tag_find.s

# target to generate assembly for a file
src/tag_find.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_find.cpp.s
.PHONY : src/tag_find.cpp.s

src/tag_impl.o: src/tag_impl.cpp.o
.PHONY : src/tag_impl.o

# target to build an object file
src/tag_impl.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_impl.cpp.o
.PHONY : src/tag_impl.cpp.o

src/tag_impl.i: src/tag_impl.cpp.i
.PHONY : src/tag_impl.i

# target to preprocess a source file
src/tag_impl.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_impl.cpp.i
.PHONY : src/tag_impl.cpp.i

src/tag_impl.s: src/tag_impl.cpp.s
.PHONY : src/tag_impl.s

# target to generate assembly for a file
src/tag_impl.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_impl.cpp.s
.PHONY : src/tag_impl.cpp.s

src/tag_parse.o: src/tag_parse.cpp.o
.PHONY : src/tag_parse.o

# target to build an object file
src/tag_parse.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse.cpp.o
.PHONY : src/tag_parse.cpp.o

src/tag_parse.i: src/tag_parse.cpp.i
.PHONY : src/tag_parse.i

# target to preprocess a source file
src/tag_parse.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse.cpp.i
.PHONY : src/tag_parse.cpp.i

src/tag_parse.s: src/tag_parse.cpp.s
.PHONY : src/tag_parse.s

# target to generate assembly for a file
src/tag_parse.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse.cpp.s
.PHONY : src/tag_parse.cpp.s

src/tag_parse_lyrics3.o: src/tag_parse_lyrics3.cpp.o
.PHONY : src/tag_parse_lyrics3.o

# target to build an object file
src/tag_parse_lyrics3.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_lyrics3.cpp.o
.PHONY : src/tag_parse_lyrics3.cpp.o

src/tag_parse_lyrics3.i: src/tag_parse_lyrics3.cpp.i
.PHONY : src/tag_parse_lyrics3.i

# target to preprocess a source file
src/tag_parse_lyrics3.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_lyrics3.cpp.i
.PHONY : src/tag_parse_lyrics3.cpp.i

src/tag_parse_lyrics3.s: src/tag_parse_lyrics3.cpp.s
.PHONY : src/tag_parse_lyrics3.s

# target to generate assembly for a file
src/tag_parse_lyrics3.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_lyrics3.cpp.s
.PHONY : src/tag_parse_lyrics3.cpp.s

src/tag_parse_musicmatch.o: src/tag_parse_musicmatch.cpp.o
.PHONY : src/tag_parse_musicmatch.o

# target to build an object file
src/tag_parse_musicmatch.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_musicmatch.cpp.o
.PHONY : src/tag_parse_musicmatch.cpp.o

src/tag_parse_musicmatch.i: src/tag_parse_musicmatch.cpp.i
.PHONY : src/tag_parse_musicmatch.i

# target to preprocess a source file
src/tag_parse_musicmatch.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_musicmatch.cpp.i
.PHONY : src/tag_parse_musicmatch.cpp.i

src/tag_parse_musicmatch.s: src/tag_parse_musicmatch.cpp.s
.PHONY : src/tag_parse_musicmatch.s

# target to generate assembly for a file
src/tag_parse_musicmatch.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_musicmatch.cpp.s
.PHONY : src/tag_parse_musicmatch.cpp.s

src/tag_parse_v1.o: src/tag_parse_v1.cpp.o
.PHONY : src/tag_parse_v1.o

# target to build an object file
src/tag_parse_v1.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_v1.cpp.o
.PHONY : src/tag_parse_v1.cpp.o

src/tag_parse_v1.i: src/tag_parse_v1.cpp.i
.PHONY : src/tag_parse_v1.i

# target to preprocess a source file
src/tag_parse_v1.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_v1.cpp.i
.PHONY : src/tag_parse_v1.cpp.i

src/tag_parse_v1.s: src/tag_parse_v1.cpp.s
.PHONY : src/tag_parse_v1.s

# target to generate assembly for a file
src/tag_parse_v1.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_parse_v1.cpp.s
.PHONY : src/tag_parse_v1.cpp.s

src/tag_render.o: src/tag_render.cpp.o
.PHONY : src/tag_render.o

# target to build an object file
src/tag_render.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_render.cpp.o
.PHONY : src/tag_render.cpp.o

src/tag_render.i: src/tag_render.cpp.i
.PHONY : src/tag_render.i

# target to preprocess a source file
src/tag_render.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_render.cpp.i
.PHONY : src/tag_render.cpp.i

src/tag_render.s: src/tag_render.cpp.s
.PHONY : src/tag_render.s

# target to generate assembly for a file
src/tag_render.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/tag_render.cpp.s
.PHONY : src/tag_render.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	cd /home/camilo/solution/basis && $(MAKE) $(MAKESILENT) -f source/port/id3lib/CMakeFiles/id3lib.dir/build.make source/port/id3lib/CMakeFiles/id3lib.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... id3lib"
	@echo "... ca2_readers.o"
	@echo "... ca2_readers.i"
	@echo "... ca2_readers.s"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... src/field.o"
	@echo "... src/field.i"
	@echo "... src/field.s"
	@echo "... src/field_binary.o"
	@echo "... src/field_binary.i"
	@echo "... src/field_binary.s"
	@echo "... src/field_integer.o"
	@echo "... src/field_integer.i"
	@echo "... src/field_integer.s"
	@echo "... src/field_string_ascii.o"
	@echo "... src/field_string_ascii.i"
	@echo "... src/field_string_ascii.s"
	@echo "... src/field_string_unicode.o"
	@echo "... src/field_string_unicode.i"
	@echo "... src/field_string_unicode.s"
	@echo "... src/frame.o"
	@echo "... src/frame.i"
	@echo "... src/frame.s"
	@echo "... src/frame_impl.o"
	@echo "... src/frame_impl.i"
	@echo "... src/frame_impl.s"
	@echo "... src/frame_parse.o"
	@echo "... src/frame_parse.i"
	@echo "... src/frame_parse.s"
	@echo "... src/frame_render.o"
	@echo "... src/frame_render.i"
	@echo "... src/frame_render.s"
	@echo "... src/globals.o"
	@echo "... src/globals.i"
	@echo "... src/globals.s"
	@echo "... src/header.o"
	@echo "... src/header.i"
	@echo "... src/header.s"
	@echo "... src/header_frame.o"
	@echo "... src/header_frame.i"
	@echo "... src/header_frame.s"
	@echo "... src/header_tag.o"
	@echo "... src/header_tag.i"
	@echo "... src/header_tag.s"
	@echo "... src/helpers.o"
	@echo "... src/helpers.i"
	@echo "... src/helpers.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/io_decorators.o"
	@echo "... src/io_decorators.i"
	@echo "... src/io_decorators.s"
	@echo "... src/io_helpers.o"
	@echo "... src/io_helpers.i"
	@echo "... src/io_helpers.s"
	@echo "... src/misc_support.o"
	@echo "... src/misc_support.i"
	@echo "... src/misc_support.s"
	@echo "... src/mp3_parse.o"
	@echo "... src/mp3_parse.i"
	@echo "... src/mp3_parse.s"
	@echo "... src/readers.o"
	@echo "... src/readers.i"
	@echo "... src/readers.s"
	@echo "... src/spec.o"
	@echo "... src/spec.i"
	@echo "... src/spec.s"
	@echo "... src/tag.o"
	@echo "... src/tag.i"
	@echo "... src/tag.s"
	@echo "... src/tag_file.o"
	@echo "... src/tag_file.i"
	@echo "... src/tag_file.s"
	@echo "... src/tag_find.o"
	@echo "... src/tag_find.i"
	@echo "... src/tag_find.s"
	@echo "... src/tag_impl.o"
	@echo "... src/tag_impl.i"
	@echo "... src/tag_impl.s"
	@echo "... src/tag_parse.o"
	@echo "... src/tag_parse.i"
	@echo "... src/tag_parse.s"
	@echo "... src/tag_parse_lyrics3.o"
	@echo "... src/tag_parse_lyrics3.i"
	@echo "... src/tag_parse_lyrics3.s"
	@echo "... src/tag_parse_musicmatch.o"
	@echo "... src/tag_parse_musicmatch.i"
	@echo "... src/tag_parse_musicmatch.s"
	@echo "... src/tag_parse_v1.o"
	@echo "... src/tag_parse_v1.i"
	@echo "... src/tag_parse_v1.s"
	@echo "... src/tag_render.o"
	@echo "... src/tag_render.i"
	@echo "... src/tag_render.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/camilo/solution/basis && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

